import { CityContext, Curiosity, WalkCandidatePlace } from "@/lib/walk/types";

const agraStops: WalkCandidatePlace[] = [
  {
    id: "agra-fort",
    title: "Agra Fort",
    shortLabel: "Fort",
    lat: 27.1795,
    lng: 78.0211,
    areaLabel: "Fort precinct",
    siteType: "fort",
    standingStatus: "standing",
    image: {
      url: "https://upload.wikimedia.org/wikipedia/commons/5/56/Agra_Fort.jpg",
      thumbUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/56/Agra_Fort.jpg/640px-Agra_Fort.jpg",
      sourcePage: "https://commons.wikimedia.org/wiki/File:Agra_Fort.jpg",
      attribution: "Wikimedia Commons",
      license: "CC BY-SA",
      width: 1600,
      height: 1067,
      imageConfidence: 0.93,
    },
    evidenceUrls: ["https://www.asiagracircle.in/agra-fort.html"],
    chronologyLabel: "16th century",
    whyItMatters: "The seat of Mughal power before and during the city's imperial peak.",
    historicalSummary: "A walled red sandstone complex where imperial decisions shaped north India.",
    sourceQuality: 0.92,
    mappableConfidence: 0.96,
    survivingConfidence: 0.96,
  },
  {
    id: "jama-masjid-agra",
    title: "Jama Masjid, Agra",
    shortLabel: "Jama Masjid",
    lat: 27.1838,
    lng: 78.0162,
    areaLabel: "Old city core",
    siteType: "mosque",
    standingStatus: "standing",
    image: {
      url: "https://upload.wikimedia.org/wikipedia/commons/2/2d/Jama_Masjid_Agra.jpg",
      thumbUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2d/Jama_Masjid_Agra.jpg/640px-Jama_Masjid_Agra.jpg",
      sourcePage: "https://commons.wikimedia.org/wiki/File:Jama_Masjid_Agra.jpg",
      attribution: "Wikimedia Commons",
      license: "CC BY-SA",
      width: 1280,
      height: 853,
      imageConfidence: 0.87,
    },
    evidenceUrls: ["https://www.asiagracircle.in/jama-masjid-agra.html"],
    chronologyLabel: "17th century",
    whyItMatters: "It anchors the lived city around imperial space, trade, and worship.",
    historicalSummary: "A congregational mosque commissioned in Shah Jahan's reign near Agra's commercial heart.",
    sourceQuality: 0.85,
    mappableConfidence: 0.93,
    survivingConfidence: 0.94,
  },
  {
    id: "moti-masjid-fort",
    title: "Moti Masjid (inside Agra Fort)",
    shortLabel: "Moti Masjid",
    lat: 27.1807,
    lng: 78.0216,
    areaLabel: "Agra Fort interior",
    siteType: "mosque",
    standingStatus: "standing",
    image: {
      url: "https://upload.wikimedia.org/wikipedia/commons/b/b6/Moti_Masjid_in_Agra_Fort.jpg",
      thumbUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/Moti_Masjid_in_Agra_Fort.jpg/640px-Moti_Masjid_in_Agra_Fort.jpg",
      sourcePage: "https://commons.wikimedia.org/wiki/File:Moti_Masjid_in_Agra_Fort.jpg",
      attribution: "Wikimedia Commons",
      license: "CC BY-SA",
      width: 1600,
      height: 1044,
      imageConfidence: 0.84,
    },
    evidenceUrls: ["https://www.asiagracircle.in/agra-fort.html"],
    chronologyLabel: "17th century",
    whyItMatters: "A courtly mosque that reveals how rule and ritual sat side by side.",
    historicalSummary: "The Pearl Mosque is one of the most refined white-marble structures in the fort.",
    sourceQuality: 0.84,
    mappableConfidence: 0.9,
    survivingConfidence: 0.92,
  },
  {
    id: "itimad-ud-daulah",
    title: "Tomb of Itimad-ud-Daulah",
    shortLabel: "Itimad-ud-Daulah",
    lat: 27.1924,
    lng: 78.0314,
    areaLabel: "Yamuna edge",
    siteType: "tomb",
    standingStatus: "standing",
    image: {
      url: "https://upload.wikimedia.org/wikipedia/commons/8/8d/Itmad_ud_Daulah_Agra.jpg",
      thumbUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8d/Itmad_ud_Daulah_Agra.jpg/640px-Itmad_ud_Daulah_Agra.jpg",
      sourcePage: "https://commons.wikimedia.org/wiki/File:Itmad_ud_Daulah_Agra.jpg",
      attribution: "Wikimedia Commons",
      license: "CC BY-SA",
      width: 1600,
      height: 900,
      imageConfidence: 0.91,
    },
    evidenceUrls: ["https://www.asiagracircle.in/itimad-ud-daulah.html"],
    chronologyLabel: "17th century",
    whyItMatters: "A bridge between earlier red sandstone idioms and later white marble grandeur.",
    historicalSummary: "A riverside mausoleum associated with Nur Jahan's family and Mughal court culture.",
    sourceQuality: 0.9,
    mappableConfidence: 0.95,
    survivingConfidence: 0.95,
  },
  {
    id: "mehtab-bagh",
    title: "Mehtab Bagh",
    shortLabel: "Mehtab Bagh",
    lat: 27.1792,
    lng: 78.0421,
    areaLabel: "North Yamuna bank",
    siteType: "garden",
    standingStatus: "partial",
    image: {
      url: "https://upload.wikimedia.org/wikipedia/commons/d/d7/Mehtab_Bagh_Agra.jpg",
      thumbUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d7/Mehtab_Bagh_Agra.jpg/640px-Mehtab_Bagh_Agra.jpg",
      sourcePage: "https://commons.wikimedia.org/wiki/File:Mehtab_Bagh_Agra.jpg",
      attribution: "Wikimedia Commons",
      license: "CC BY-SA",
      width: 1280,
      height: 853,
      imageConfidence: 0.83,
    },
    evidenceUrls: ["https://www.asiagracircle.in/mehtab-bagh.html"],
    chronologyLabel: "17th century",
    whyItMatters: "It shows how imperial planning used river, garden, and monument as one composition.",
    historicalSummary: "A charbagh garden framing the Yamuna-facing vista of Agra's imperial zone.",
    sourceQuality: 0.82,
    mappableConfidence: 0.9,
    survivingConfidence: 0.8,
  },
  {
    id: "kinari-bazaar",
    title: "Kinari Bazaar",
    shortLabel: "Kinari Bazaar",
    lat: 27.182,
    lng: 78.0137,
    areaLabel: "Old city lanes",
    siteType: "bazaar",
    standingStatus: "trace",
    image: {
      url: "https://upload.wikimedia.org/wikipedia/commons/1/1f/Kinari_Bazaar_Agra.jpg",
      thumbUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1f/Kinari_Bazaar_Agra.jpg/640px-Kinari_Bazaar_Agra.jpg",
      sourcePage: "https://commons.wikimedia.org/wiki/File:Kinari_Bazaar_Agra.jpg",
      attribution: "Wikimedia Commons",
      license: "CC BY-SA",
      width: 1200,
      height: 800,
      imageConfidence: 0.75,
    },
    evidenceUrls: ["https://www.agra.nic.in/tourist-place/kinari-bazar/"],
    chronologyLabel: "continuing urban fabric",
    whyItMatters: "Shows how imperial-era circulation persists in market streets and craft trade.",
    historicalSummary: "A dense market corridor linking the ceremonial and commercial old city.",
    sourceQuality: 0.74,
    mappableConfidence: 0.85,
    survivingConfidence: 0.72,
  },
];

export function getAgraFallbackContext(duration: string, curiosity: Curiosity): CityContext {
  return {
    city: "Agra",
    normalizedCity: "agra",
    duration,
    curiosity,
    resolvedCuriosity: curiosity === "surprise me" ? "power" : curiosity,
    curiosityReason: curiosity === "surprise me" ? "Agra is strongest on imperial power routes." : undefined,
    center: [78.0218, 27.1751],
    bounds: [[77.995, 27.15], [78.055, 27.205]],
    candidates: agraStops,
    coverage: "strong",
    warnings: [],
  };
}
